### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by mathougui** [algolia/react-instantsearch-widget-color-refinement-list#1]
@FabienMotte I don't understand the purpose of [this](https://github.com/algolia/react-instantsearch-widget-color-refinement-list/blob/9aed1714f0596a693a7113ca122c5670e6340536/src/lib/component.tsx#L62) line. Just before you concat the refinedItems with the non refined until you hit the limit value, so why this condition?

**Comment by FabienMotte** [comment]
Hey, thanks for the code review, I've done some [refactoring recently and also added comments](https://github.com/algolia/react-instantsearch-widget-color-refinement-list/blob/master/src/lib/component.tsx#L87), now it should be more clear.
